export interface Character {
  name: string;
  cost: number;
  isGiant: boolean;
  transformationGroup?: string; // Gruppo di trasformazione (opzionale)
}


export const CHARACTERS: Character[] = [
  { name: 'mr. satan', cost: 1, isGiant: false },
  { name: 'videl', cost: 2, isGiant: false },
  { name: 'muten base', cost: 2, isGiant: false , transformationGroup: 'muten'},
  { name: 'muten maxpower', cost: 2, isGiant: false , transformationGroup: 'muten'},
  { name: 'rif', cost: 2, isGiant: false },
  { name: 'yajirobe', cost: 2, isGiant: false },
  { name: 'saibaimen', cost: 2, isGiant: false },
  { name: 'guldo', cost: 2, isGiant: false },
  { name: 'frieza soldier', cost: 2, isGiant: false },
  { name: 'spopovich', cost: 2, isGiant: false },
  { name: 'teen goku', cost: 3, isGiant: false },
  { name: 'kid gohan', cost: 3, isGiant: false },
  { name: 'krillin', cost: 3, isGiant: false },
  { name: 'yamcha', cost: 3, isGiant: false },
  { name: 'cell jr.',cost:3 , isGiant: false },
  { name: 'pan',cost:3 , isGiant: false },
  { name: 'raditz',cost:3 , isGiant: false },
  { name: 'nappa',cost:3 , isGiant: false },
  { name: 'zarbon',cost:3 , isGiant: false ,transformationGroup: 'zarbon'},
  { name: 'super-zarbon',cost:3 , isGiant: false,transformationGroup: 'zarbon' },
  { name: 'dodoria',cost:3 , isGiant: false },
  { name: 'cui',cost:3 , isGiant: false },
  { name: 'recoome',cost:3 , isGiant: false },
  { name: 'jeice',cost:3 , isGiant: false },
  { name: 'burter',cost:3 , isGiant: false },
  { name: 'babidi',cost:3 , isGiant: false },
  { name: 'base goku z1',cost:4 , isGiant: false },
  { name: 'mini goku daima',cost:4 , isGiant: false },
  { name: 'vegeta scouter',cost:4 , isGiant: false },
  { name: 'base teen gohan',cost:4 , isGiant: false },
  { name: 'base adult gohan',cost:4 , isGiant: false },
  { name: 'great sayaman',cost:4 , isGiant: false },
  { name: 'piccolo',cost:4 , isGiant: false },
  { name: 'nail',cost:4 , isGiant: false },
  { name: 'tensing',cost:4 , isGiant: false },
  { name: 'base sword trunks',cost:4 , isGiant: false },
  { name: 'kid trunks',cost:4 , isGiant: false },
  { name: 'base goten',cost:4 , isGiant: false },
  { name: 'uub',cost:4 , isGiant: false },
  { name: 'bardack',cost:4 , isGiant: false },
  { name: 'ginyu',cost:4 , isGiant: false },
  { name: 'king cold',cost:4 , isGiant: false },
  { name: 'android 19',cost:4 , isGiant: false },
  { name: 'dr.gero',cost:4 , isGiant: false },
  { name: 'super garlic jr.',cost:4 , isGiant: false },
  { name: 'dr. Wheelo',cost:4 , isGiant: true },
  { name: 'turles',cost:4 , isGiant: false },
  { name: 'lord slug',cost:4 , isGiant: false },
  { name: 'tapion',cost:4 , isGiant: false },
  { name: 'base goku z2',cost:5 , isGiant: false },
  { name: 'ssj goku z2',cost:5 , isGiant: false },
  { name: 'base goku z3',cost:5 , isGiant: false },
  { name: 'base goku super',cost:5 , isGiant: false },
  { name: 'base goku gt',cost:5 , isGiant: false },
  { name: 'greate ape vegeta',cost:5 , isGiant: true },
  { name: 'base vegeta z1',cost:5 , isGiant: false },
  { name: 'base vegeta z2',cost:5 , isGiant: false },
  { name: 'base vegeta super',cost:5 , isGiant: false },
  { name: 'base future gohan',cost:5 , isGiant: false },
  { name: 'piccolo w/kami',cost:5 , isGiant: false },
  { name: 'ssj sword trunks',cost:5 , isGiant: false },
  { name: 'base melee trunks',cost:5 , isGiant: false },
  { name: 'base future trunks super',cost:5 , isGiant: false },
  { name: 'ssj kid trunks',cost:5 , isGiant: false },
  { name: 'ssj goten',cost:5 , isGiant: false },
  { name: 'friezer 1 forma',cost:5 , isGiant: false },
  { name: 'friezer 2 forma',cost:5 , isGiant: false },
  { name: 'friezer 3 forma',cost:5 , isGiant: false },
  { name: 'cell 1 forma',cost:5 , isGiant: false },
  { name: 'cell 2 forma',cost:5 , isGiant: false },
  { name: 'androide 16',cost:5 , isGiant: false },
  { name: 'androide 17 z',cost:5 , isGiant: false },
  { name: 'androide 18',cost:5 , isGiant: false },
  { name: 'base broly z',cost:5 , isGiant: false },
  { name: 'giant lord slug',cost:5 , isGiant: true },
  { name: 'base broly super',cost:5 , isGiant: false },
  { name: 'androide 13',cost:5 , isGiant: false },
  { name: 'janemba base',cost:5 , isGiant: true },
  { name: 'baby vegeta',cost:5 , isGiant: false },
  { name: 'base goku black',cost:5 , isGiant: false },
  { name: 'zamasu',cost:5 , isGiant: false },
  { name: 'base cabba',cost:5 , isGiant: false },
  { name: 'base caulifla',cost:5 , isGiant: false },
  { name: 'base kale',cost:5 , isGiant: false },
  { name: 'bergamo',cost:5 , isGiant: false },
  { name: 'ribrianne',cost:5 , isGiant: false },
  { name: 'kakunsa',cost:5 , isGiant: false },
  { name: 'roasie',cost:5 , isGiant: false },
  { name: 'ssj goku z3',cost:6 , isGiant: false },
  { name: 'ssj2 goku z3',cost:6 , isGiant: false },
  { name: 'ssj goku super',cost:6 , isGiant: false },
  { name: 'ssj goku gt',cost:6 , isGiant: false },
  { name: 'ssj vegeta z1',cost:6 , isGiant: false },
  { name: 'super vegeta z1',cost:6 , isGiant: false },
  { name: 'ssj vegeta super',cost:6 , isGiant: false },
  { name: 'ssj2 vegeta super',cost:6 , isGiant: false },
  { name: 'ssj teen gohan',cost:6 , isGiant: false },
  { name: 'ssj adult gohan',cost:6 , isGiant: false },
  { name: 'ssj future gohan',cost:6 , isGiant: false },
  { name: 'ssj melee trunks',cost:6 , isGiant: false },
  { name: 'super trunks',cost:6 , isGiant: false },
  { name: 'ssj future trunks super',cost:6 , isGiant: false },
  { name: 'base gotenks',cost:6 , isGiant: false },
  { name: 'friezer 4 forma',cost:6 , isGiant: false },
  { name: 'mecha friezer',cost:6 , isGiant: false },
  { name: 'friezer super',cost:6 , isGiant: false },
  { name: 'perfect cell',cost:6 , isGiant: false },
  { name: 'majin buu fat',cost:6 , isGiant: false },
  { name: 'evil buu',cost:6 , isGiant: false },
  { name: 'super buu',cost:6 , isGiant: false },
  { name: 'majuub',cost:6 , isGiant: false },
  { name: 'androide 17 super',cost:6 , isGiant: false },
  { name: 'darbula',cost:6 , isGiant: false },
  { name: 'cooler',cost:6 , isGiant: false },
  { name: 'hirudegarn',cost:6 , isGiant: false },
  { name: 'super baby',cost:6 , isGiant: false },
  { name: 'frost',cost:6 , isGiant: false },
  { name: 'ssj cabba',cost:6 , isGiant: false },
  { name: 'ssj kale',cost:6 , isGiant: false },
  { name: 'base kefla',cost:6 , isGiant: false },
  { name: 'dyspo',cost:6 , isGiant: false },
  { name: 'ssj3 goku z3',cost:7 , isGiant: false },
  { name: 'ssj god goku super',cost:7 , isGiant: false },
  { name: 'ssj3 goku gt',cost:7 , isGiant: false },
  { name: 'majin vegeta',cost:7 , isGiant: false },
  { name: 'ssj god vegeta',cost:7 , isGiant: false },
  { name: 'ssj2 teen gohan',cost:7 , isGiant: false },
  { name: 'ssj2 adult gohan',cost:7 , isGiant: false },
  { name: 'ultimate gohan',cost:7 , isGiant: false },
  { name: 'base vegito',cost:7 , isGiant: false },
  { name: 'base gogeta',cost:7 , isGiant: false },
  { name: 'ssj gotenks',cost:7 , isGiant: false },
  { name: 'friezer full power',cost:7 , isGiant: false },
  { name: 'super perfect cell',cost:7 , isGiant: false },
  { name: 'buutenks',cost:7 , isGiant: false },
  { name: 'buuhan',cost:7 , isGiant: false },
  { name: 'kid buu',cost:7 , isGiant: false },
  { name: 'ssj broly z',cost:7 , isGiant: false },
  { name: 'ssj broly super',cost:7 , isGiant: false },
  { name: 'final form cooler',cost:7 , isGiant: false },
  { name: 'metal cooler',cost:7 , isGiant: false },
  { name: 'fusion android 13',cost:7 , isGiant: false },
  { name: 'full power bojack',cost:7 , isGiant: false },
  { name: 'super janemba',cost:7 , isGiant: false },
  { name: 'super baby 2',cost:7 , isGiant: false },
  { name: 'great ape baby',cost:7 , isGiant: true },
  { name: 'syn shenron',cost:7 , isGiant: false },
  { name: 'ssj2 cabba',cost:7 , isGiant: false },
  { name: 'ssj2 caulifla',cost:7 , isGiant: false },
  { name: 'ssj kale berserk',cost:7 , isGiant: false },
  { name: 'ssj kefla',cost:7 , isGiant: false },
  { name: 'base toppo',cost:7 , isGiant: false },
  { name: 'ssj blue goku super',cost:8 , isGiant: false },
  { name: 'ui sign goku',cost:8 , isGiant: false },
  { name: 'ssj4 goku gt',cost:8 , isGiant: false },
  { name: 'ssj blue vegeta super',cost:8 , isGiant: false },
  { name: 'ssj4 vegeta',cost:8 , isGiant: false },
  { name: 'super vegito',cost:8 , isGiant: false },
  { name: 'super gogeta z',cost:8 , isGiant: false },
  { name: 'ssj gogeta super',cost:8 , isGiant: false },
  { name: 'ssj3 gotenks',cost:8 , isGiant: false },
  { name: 'golden friezer',cost:8 , isGiant: false },
  { name: 'omega shenron',cost:8 , isGiant: false },
  { name: 'ssj rose goku black',cost:8 , isGiant: false },
  { name: 'merged zamasu',cost:8 , isGiant: false },
  { name: 'it',cost:8 , isGiant: false },
  { name: 'ssj2 kefla',cost:8 , isGiant: false },
  { name: 'jiren',cost:8 , isGiant: false },
  { name: 'god toppo',cost:8 , isGiant: false },
  { name: 'anilaza',cost:8 , isGiant: true },
  { name: 'mui goku super',cost:9 , isGiant: false },
  { name: 'lssj broly z',cost:9 , isGiant: false },
  { name: 'ssj broly fullpower super',cost:9 , isGiant: false },
  { name: 'fused zamasu corrupted',cost:9 , isGiant: false },
  { name: 'jiren full power',cost:9 , isGiant: false },
  { name: 'vegito blu',cost:10 , isGiant: false },
  { name: 'gogeta blu',cost:10 , isGiant: false },
  { name: 'gogeta ssj4',cost:10 , isGiant: false },
  { name: 'beerus',cost:10 , isGiant: false },
  { name: 'whis',cost:10 , isGiant: false }
];